services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - honey_network
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - MONGODB_URI=mongodb://honey:password123@mongodb:27017/honey_shop?authSource=admin
      - PORT=5001
    ports:
      - "5001:5001"
    depends_on:
      - mongodb
    networks:
      - honey_network
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    container_name: honey_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=honey
      - MONGO_INITDB_ROOT_PASSWORD=password123
    networks:
      - honey_network
    restart: unless-stopped

  mongo-express:
    image: mongo-express:latest
    container_name: honey_mongo_express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=honey
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password123
      - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on:
      - mongodb
    networks:
      - honey_network
    restart: unless-stopped

volumes:
  mongodb_data:

networks:
  honey_network:
    driver: bridge