AWSTemplateFormatVersion: '2010-09-09'
Description: 'ECS Services for Honey Shop'

Parameters:
  Environment:
    Type: String
    Default: production
  
  ClusterName:
    Type: String
    Description: Name of the ECS cluster
  
  FrontendImage:
    Type: String
    Description: Frontend Docker image URI
  
  BackendImage:
    Type: String
    Description: Backend Docker image URI
  
  DocDBEndpoint:
    Type: String
    Description: DocumentDB endpoint
  
  DocDBUsername:
    Type: String
    Description: DocumentDB username
  
  DocDBPassword:
    Type: String
    Description: DocumentDB password
    NoEcho: true

Resources:
  # Task Definitions
  FrontendTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub ${Environment}-honey-frontend
      RequiresCompatibilities:
        - FARGATE
      NetworkMode: awsvpc
      Cpu: '256'
      Memory: '512'
      ContainerDefinitions:
        - Name: frontend
          Image: !Ref FrontendImage
          PortMappings:
            - ContainerPort: 80
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref FrontendLogGroup
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: frontend

  BackendTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub ${Environment}-honey-backend
      RequiresCompatibilities:
        - FARGATE
      NetworkMode: awsvpc
      Cpu: '256'
      Memory: '512'
      ContainerDefinitions:
        - Name: backend
          Image: !Ref BackendImage
          PortMappings:
            - ContainerPort: 5001
          Environment:
            - Name: MONGODB_URI
              Value: !Sub mongodb://${DocDBUsername}:${DocDBPassword}@${DocDBEndpoint}:27017/honey_shop?replicaSet=rs0&readPreference=secondaryPreferred
            - Name: PORT
              Value: '5001'
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref BackendLogGroup
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: backend

  # Services
  FrontendService:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: !Sub ${Environment}-honey-frontend
      Cluster: !Ref ClusterName
      TaskDefinition: !Ref FrontendTaskDefinition
      DesiredCount: 2
      LaunchType: FARGATE
      LoadBalancers:
        - ContainerName: frontend
          ContainerPort: 80
          TargetGroupArn: !Ref FrontendTargetGroup

  BackendService:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: !Sub ${Environment}-honey-backend
      Cluster: !Ref ClusterName
      TaskDefinition: !Ref BackendTaskDefinition
      DesiredCount: 2
      LaunchType: FARGATE
      LoadBalancers:
        - ContainerName: backend
          ContainerPort: 5001
          TargetGroupArn: !Ref BackendTargetGroup

  # CloudWatch Log Groups
  FrontendLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /ecs/${Environment}-honey-frontend
      RetentionInDays: 30

  BackendLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /ecs/${Environment}-honey-backend
      RetentionInDays: 30

  # Target Groups
  FrontendTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Sub ${Environment}-honey-frontend
      Port: 80
      Protocol: HTTP
      VpcId: !Ref VPC
      TargetType: ip
      HealthCheckPath: /
      HealthCheckIntervalSeconds: 30
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 3

  BackendTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Sub ${Environment}-honey-backend
      Port: 5001
      Protocol: HTTP
      VpcId: !Ref VPC
      TargetType: ip
      HealthCheckPath: /api/health
      HealthCheckIntervalSeconds: 30
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 3

Outputs:
  FrontendServiceName:
    Description: Frontend Service Name
    Value: !GetAtt FrontendService.Name

  BackendServiceName:
    Description: Backend Service Name
    Value: !GetAtt BackendService.Name
