version: '3.8'

services:
  frontend:
    image: honey-shop-frontend:latest
    depends_on:
      - backend
    networks:
      - honey_network
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=PathPrefix(`/`)"
      - "traefik.http.routers.frontend.entrypoints=web"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"

  backend:
    image: honey-shop-backend:latest
    environment:
      - MONGODB_URI=mongodb://honey:${MONGO_PASSWORD}@mongodb:27017/honey_shop?authSource=admin
      - PORT=5001
      - NODE_ENV=production
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - mongodb
    networks:
      - honey_network
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=PathPrefix(`/api`)"
      - "traefik.http.routers.backend.entrypoints=web"
      - "traefik.http.services.backend.loadbalancer.server.port=5001"

  mongodb:
    image: mongo:6.0
    container_name: honey_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    environment:
      - MONGO_INITDB_ROOT_USERNAME=honey
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    networks:
      - honey_network
    restart: unless-stopped
    command: mongod --auth --bind_ip_all

  traefik:
    image: traefik:v2.10
    container_name: honey_traefik
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080" # Traefik dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - honey_network
    restart: unless-stopped
    command:
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"

volumes:
  mongodb_data:
    driver: local

networks:
  honey_network:
    driver: bridge
