version: '3.8'

services:
  frontend:
    build:
      context: ..
      dockerfile: Dockerfile.frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - honey_network
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`your-domain.com`)"
      - "traefik.http.routers.frontend.entrypoints=web"

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    environment:
      - MONGODB_URI=mongodb://honey:${MONGO_PASSWORD}@mongodb:27017/honey_shop?authSource=admin
      - PORT=5001
      - NODE_ENV=production
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - "5001:5001"
    depends_on:
      - mongodb
    networks:
      - honey_network
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`api.your-domain.com`)"
      - "traefik.http.routers.backend.entrypoints=web"

  mongodb:
    image: mongo:6.0
    container_name: honey_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    environment:
      - MONGO_INITDB_ROOT_USERNAME=honey
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    networks:
      - honey_network
    restart: unless-stopped
    command: mongod --auth --bind_ip_all

  traefik:
    image: traefik:v2.10
    container_name: honey_traefik
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080" # Traefik dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik:/etc/traefik
      - ./certificates:/certificates
    networks:
      - honey_network
    restart: unless-stopped
    command:
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.letsencrypt.acme.email=your-email@example.com"
      - "--certificatesresolvers.letsencrypt.acme.storage=/etc/traefik/acme.json"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"

volumes:
  mongodb_data:
    driver: local

networks:
  honey_network:
    driver: bridge
